name: mappa
description: Minimal offline map navigation app using OpenStreetMap and device GPS.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^6.0.0
  geolocator: ^9.0.0
  latlong2: ^0.9.0
  shared_preferences: ^2.5.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
